# -*- coding: utf-8 -*-
"""Actividad_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BnXWFUZISkvo0s2xcGllsRTtDSg-y6i7
"""

class Cuenta:
    def __init__(self, titular="Oscar", cantidad=5):
        self.titular=titular
        self.cantidad=cantidad
    def mostrar(self):
        print(f"La cuenta es de {self.titular} y tiene un saldo de {self.cantidad} dolares")
    def ingresar(self, cantidad):
          self.cantidad+=cantidad
          if cantidad<0:
            print("")
          else:
            print(f"Usted ingreso {cantidad} dolares a la cuenta y ahora tiene {self.cantidad}")
    def retirar(self,cantidad):
        print (f"Usted retiró {cantidad} y su cuenta quedó en {self.cantidad-cantidad}")
cuenta1=Cuenta()
cuenta1.mostrar()
cuenta1.ingresar(125)
cuenta1.retirar(90)